Update coverage.yml

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -7,6 +7,9 @@ on:
 jobs:
   run:
     runs-on: ubuntu-latest
+    env:
+      COVERAGE_SINGLE: 70
+      COVERAGE_TOTAL: 70
     steps:
       - uses: actions/checkout@v2
       - name: Set up Python 3.9
@@ -22,7 +25,48 @@ jobs:
           pip install coverage
           coverage run -m unittest discover
           coverage report -m
-      - name: Upload Coverage to Codecov
-        uses: codecov/codecov-action@v1
+      - name: pytest
+        id: pytest
+        uses: alexanderdamiani/pytester-cov@v1.0.1
         with:
-          token: "8bff81623296491d8ff36a39112e841f"
+          pytest-root-dir: '.'
+          cov-omit-list: 'tests/*'
+          cov-threshold-single: ${{ env.COVERAGE_TOTAL }}
+          cov-threshold-total: ${{ env.COVERAGE_SINGLE }}
+
+      - name: Coverage single fail - new issue
+        if: ${{ steps.pytest.outputs.cov-threshold-single-fail == 'true' }}
+        uses: nashmaniac/create-issue-action@v1.1
+        with:
+          title: Pytest coverage single falls below minimum ${{ env.COVERAGE_SINGLE }}
+          token: ${{secrets.GITHUB_TOKEN}}
+          assignees: ${{github.actor}}
+          labels: worflow-failed
+          body: ${{ steps.pytest.outputs.output-table }}
+
+      - name: Coverage single fail - exit
+        if: ${{ steps.pytest.outputs.cov-threshold-single-fail == 'true' }}
+        run: |
+          echo "cov single fail ${{ steps.pytest.outputs.cov-threshold-single-fail }}"
+          exit 1
+
+      - name: Coverage total fail - new issue
+        if: ${{ steps.pytest.outputs.cov-threshold-total-fail == 'true' }}
+        uses: nashmaniac/create-issue-action@v1.1
+        with:
+          title: Pytest coverage total falls below minimum ${{ env.COVERAGE_TOTAL }}
+          token: ${{secrets.GITHUB_TOKEN}}
+          assignees: ${{github.actor}}
+          labels: worflow-failed
+          body: ${{ steps.pytest.outputs.output-table }}
+
+      - name: Coverage total fail - exit
+        if: ${{ steps.pytest.outputs.cov-threshold-total-fail == 'true' }}
+        run: |
+          echo "cov single fail ${{ steps.pytest.outputs.cov-threshold-total-fail }}"
+          exit 1
+
+      - name: Commit pytest coverage table
+        uses: peter-evans/commit-comment@v1
+        with:
+          body: ${{ steps.pytest.outputs.output-table }}
